portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolios.urls'))
]

portfolios/urls.py
'''Defines URL patterns for portfolios'''

from django.urls import path

from . import views

app_name = 'portfolios'
urlpatterns = [
    # home page
    path('', views.index, name='index'),
    path('projects', views.projects, name='projects'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contactj')
]

portfolios/models.py
from django.db import models

# Create your models here.

portfolios/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    # Home page
    return render(request, 'portfolios/index.html')

def projects(request):
    # Projects page
    return render(request, 'portfolios/projects.html')

def contact(request):
    # Contact page
    return render(request, 'portfolios/contact.html')

def about(request):
    # About page
    return render(request, 'portfolios/about.html')

portfolios/templates/portfolios/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>franklinjonescodes</title>

    <!-- CSS -->
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand" style='color: blue;' id='brand' href="#">FJ</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" id='nav-links' href="{% url 'portfolios:projects' %}">PROJECTS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id='nav-links' href="#">RESUME</a>
          </li>
          <li class="nav-item">
		  <a class="nav-link" id='nav-links' href="{% url 'portfolios:about' %}">ABOUT</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</html>

{% block content %} {% endblock content %}

portfolios/templates/portfolios/index.html
{% extends 'portfolios/base.html' %}
{% block content %}
{% load static %}
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>franklinjonescodes</title>

  <!--favicon -->
  <link rel="icon" href="{% static 'portfolios/img/coding.png' %}">

  <!-- css -->
  <link rel='stylesheet' href="{% static 'portfolios/css/styles.css'%}">

  <!--bootstrap -->
  {% bootstrap_css %}

  <!-- google fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700&display=swap" rel="stylesheet">
</head>

<body>
  <!-- Main -->
  <section>
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-6">
          <h2 class="main-text">Hi, I'm Franklin</h2>
	  <h1 class='main-text2'>Web-developer UI & UX Designer</h1>
          <p class="main-paragraph">Based out of Tampa, Florida, I create modern and adaptive internet projects to help businesses do better in the digital marketplace. </p>
          <button class="main-btn">Resume</button>
        </div>

        <div class="col-lg-6">
          <img class='desk-img' src="{% static 'portfolios/img/desk.jpg'%}" alt="">
	  <div class='icons'>
	    <a href='https://github.com/FranklinJamesJones89' target='blank'><i class="fa-brands fa-github fa-2x" style='color: black;'></i></a>
	    <a href='https://www.linkedin.com/in/franklin-jones-156539220/' target='blank'><i class="fa-brands fa-linkedin fa-2x" style='color: black;'></i></a>
	    <a href='mailto:fjones89@icloud.com' target='blank'><i class="fa-solid fa-envelope fa-2x" style='color: black;'></i></a>
	  </div>
        </div>
      </div>
    </div>
  </section>
 
  <!-- About -->
  <section>
    <div class='about-container'>
      <h1 class='about-header'>Personal Info</h1>
      <p class='about-paragraph'>Get to know me</p>
      
      <div class="about-container-fluid">
        <div class="row">
          <div class="col-lg-6">
	    <h1 class='about-greeting'>Hello!</h1>
	    <p class='about-description'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          </div>

          <div class="col-lg-6">
            <h1 class='about-skills'>Skills</h1>
	    
	    <div class='skills-container'>
 	      <div class='row'>
	        <div class='col-lg-3'>
		  <i class="fa-brands fa-python skill-icon fa-4x"></i>
		  <p>Python</p>
		</div>
	        <div class='col-lg-3'>
		  <i class="fa-brands fa-html5 fa-4x"></i>
		  <p>HTML</p>
		</div>
	        <div class='col-lg-3'>
		  <i class="fa-brands fa-square-js skill-icon fa-4x"></i>
		  <p>Javascript</p>
		</div>
	        <div class='col-lg-3'>
		  <i class="fa-solid fa-database fa-4x"></i>
		  <p>MongodDB</p>
		</div>
	      </div> 
	    </div>
	    
	    <div class='skills-container'>
 	      <div class='row'>
	        <div class='col-lg-4'>
		  <i class="fa-brands fa-node fa-4x"></i>
		  <p>Node.js</p>
		</div>
	        <div class='col-lg-4'>
		  <i class="fa-brands fa-react fa-4x react-icon"></i>
		  <p>React</p>
		</div>
	        <div class='col-lg-4'>
		  <i class="fa-brands fa-css3-alt fa-4x"></i>
		  <p>CSS</p>
		</div>
	      </div> 
	    </div>
	    
	    <div class='skills-container'>
 	      <div class='row'>
	        <div class='col-lg-6'>
			<!--<i class="fa-brands fa-wordpress fa-4x"></i>-->
		  <h1>dj</h1>
		  <p>Django</p>
		</div>
	        <div class='col-lg-6'>
		  <i class="fa-brands fa-git-alt fa-4x"></i>
		  <p>Git</p>
		</div>
	      </div> 
	    </div>
	    
	    <div class='skills-container'>
 	      <div class='row'>
	        <div class='col-lg-12'>
		  <i class="fa-brands fa-linux fa-4x"></i>
		  <p>Linux</p>
		</div>
	      </div> 
	    </div>
          
	  </div>
        </div>
      </div>
     
    </div>
  </section>


  <!-- Projects --> 
  <h1 class='projects-header'>My Projects</h1>

  <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <img src="http://bistromilliards.herokuapp.com/static/bistro_milliards/img/millitapas2.32be1abe7f27.webp"class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Bistroy Milliards</text>

            <div class="card-body">
              <p class="card-text">Web app for the Italian Restaurant Bistro Milliard based out of Hallowell, Maine</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-dark">View Code</button>
                  <button type="button" class="btn btn-sm btn-outline-dark">Visit Site</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg src="http://bistromilliards.herokuapp.com/static/bistro_milliards/img/millitapas2.32be1abe7f27.webp"class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://bistromilliards.herokuapp.com/static/bistro_milliards/img/millitapas2.32be1abe7f27.webp" href="http://bistromilliards.herokuapp.com/static/bistro_milliards/img/millitapas2.32be1abe7f27.webp"role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

 
  <!-- Footer --> 
  <section>
    <p class='date'></p>
  </section>

  <!-- Javascript -->
  <script src="{% static 'portfolios/js/index.js' %}"></script>
  <script src="https://kit.fontawesome.com/3ff46289c8.js" crossorigin="anonymous"></script>

</body>
</html>

{% endblock content %}

portfolios/templates/portfolios/projects.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
</head>
<body>
	<h1>Hello world</h1>
</body>
</html>